#!/usr/bin/env bash
# Pick Ollama model tier from available RAM (8GB guests need 1.5B for aider).
set -euo pipefail

HABITAT_ROOT="${HABITAT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
ISSUE_AGENT_HOME="${ISSUE_AGENT_HOME:-$HOME/issue-agent}"
CFG="$ISSUE_AGENT_HOME/config.local.toml"

mem_gb="$(awk '/MemTotal/ {printf "%d", $2/1024/1024}' /proc/meminfo 2>/dev/null || echo 16)"
if [[ "$mem_gb" -lt 10 ]] || [[ "${HABITAT_LIGHT:-}" == 1 ]]; then
  model="ollama/qwen2.5-coder:1.5b"
else
  model="ollama/qwen2.5-coder:7b"
fi

mkdir -p "$(dirname "$CFG")"
if [[ -f "$CFG" ]] && grep -qF "$model" "$CFG" 2>/dev/null; then
  exit 0
fi

cat > "$CFG" <<EOF
# Generated by agent-habitat configure-model-tier (RAM=${mem_gb}GB)
model = "$model"
triage_model = "customs-1.5b"
EOF
printf '[tier] RAM %sGB → %s\n' "$mem_gb" "$model"